import = [
    "~/.config/alacritty/themes/themes/google.toml"
]

[font]
size = 9

[font.bold]
family = "FiraCodeNerdFont"
style = "Bold"

[font.italic]
family = "FiraCodeNerdFont"
style = "Italic"

[font.normal]
family = "FiraCodeNerdFont"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = " "
key = "Space"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BR"
key = "R"
mods = "Command"

[window]
decorations = "full"
dynamic_padding = true
opacity = 1
title = "A"

[window.dimensions]
columns = 75
lines = 30

[window.padding]
x = 0
y = 0
